# Generated by Django 4.2.20 on 2025-06-10 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_mealplan_mealplanentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "analytics",
            "0002_recipecomment_ip_address_recipecomment_session_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipelike",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipelike",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="recipecomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_recipe_comments_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipelike",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_likes",
                to="recipe.recipe",
            ),
        ),
    ]
