# Generated by Django 4.2.20 on 2025-06-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
