# Generated by Django 4.2.20 on 2025-05-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="recipe_videos/"),
        ),
    ]
