# Generated by Django 4.2.20 on 2025-05-23 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_recipe_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(
                blank=True, help_text="List main ingredients separated by commas"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_items",
                to="recipe.recipe",
            ),
        ),
    ]
