# Generated by Django 4.2.20 on 2025-05-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_recipe_ingredients_alter_ingredient_recipe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AlterField(
            model_name="likedrecipe",
            name="liked_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="step",
            unique_together={("recipe", "order")},
        ),
    ]
