# Generated by Django 4.2.20 on 2025-05-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_ingredient_options_remove_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={"ordering": ["id"]},
        ),
        migrations.AlterUniqueTogether(
            name="step",
            unique_together={("recipe", "description")},
        ),
        migrations.RemoveField(
            model_name="step",
            name="order",
        ),
    ]
