# Generated by Django 4.2.20 on 2025-05-26 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0006_comment_username_rating_username_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("recipe", "user")},
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="recipe.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="username",
            field=models.CharField(blank=True, default="Anonymous", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="username",
            field=models.CharField(blank=True, default="Anonymous", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("recipe", "username"), ("recipe", "user")},
        ),
        migrations.RemoveField(
            model_name="rating",
            name="updated_at",
        ),
    ]
