# Generated by Django 4.2.20 on 2025-06-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_mealplan_mealplanentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="video_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
