# Generated by Django 4.2.20 on 2025-06-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0009_recipe_image_url_recipe_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
