# Generated by Django 4.2.20 on 2025-06-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amazon_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
