# Generated by Django 4.2.20 on 2025-06-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_platformingredient_platformingredientcart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformingredient",
            name="image_url",
            field=models.FileField(
                blank=True, max_length=1000, null=True, upload_to="ingredients"
            ),
        ),
    ]
