# Generated by Django 4.2.20 on 2025-06-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_platformingredient_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformingredient",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
