# Generated by Django 4.2.20 on 2025-06-12 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0006_alter_platformingredient_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformingredientcart",
            name="session_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="platformingredientcart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platformingredientcart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="platformingredientcart",
            unique_together={("user", "session_key")},
        ),
    ]
