# Generated by Django 4.2.20 on 2025-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_platformingredientcart_session_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "guest_sessions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="platformingredientcart",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="platformingredientcart",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="platformingredientcart",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("session_key__isnull", True), ("user__isnull", False)),
                    models.Q(("session_key__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="cart_owner_constraint",
            ),
        ),
    ]
