# Generated by Django 4.2.20 on 2025-06-10 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0008_mealplan_mealplanentry"),
        (
            "recommendations",
            "0002_alter_recipeview_recipe_alter_recipeview_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeview",
            name="interaction_type",
            field=models.CharField(default="view", max_length=50),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="cooking_skill_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="disliked_ingredients",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="preferred_cooking_time",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="cuisine_preferences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="dietary_needs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name="recipeview",
            unique_together={("user", "recipe")},
        ),
        migrations.CreateModel(
            name="IngredientSearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredients", models.JSONField()),
                ("results", models.JSONField()),
                ("search_timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-search_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="recipe.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-created_at"],
                "unique_together": {("user", "recipe")},
            },
        ),
    ]
