# Generated by Django 4.2.20 on 2025-04-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("USER", "Regular User"), ("CHEF", "Chef")],
                default="USER",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ChefProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("ITALIAN", "Italian Cuisine"),
                            ("FRENCH", "French Cuisine"),
                            ("AFRICAN", "Afican Cuisine"),
                            ("INDIAN", "Indian Cuisine"),
                            ("CHINESE", "Chinese Cuisine"),
                            ("JAPANESE", "Japanese Cuisine"),
                            ("MEXICAN", "Mexican Cuisine"),
                            ("MEDITERRANEAN", "Mediterranean Cuisine"),
                            ("AMERICAN", "American Cuisine"),
                            ("THAI", "Thai Cuisine"),
                            ("OTHER", "Other Cuisine"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "certification",
                    models.FileField(
                        blank=True, null=True, upload_to="chef/chef_certifications/"
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "issuing_authority",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "identity_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="chef/chef_identity_proofs/"
                    ),
                ),
                (
                    "food_safety_certification",
                    models.FileField(
                        blank=True, null=True, upload_to="chef/food_safety_certs/"
                    ),
                ),
                ("has_accepted_terms", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chef_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
