# Generated by Django 4.2.20 on 2025-05-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_customuser_role_chefprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chefprofile",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("ITALIAN", "Italian Cuisine"),
                    ("FRENCH", "French Cuisine"),
                    ("AFRICAN", "African Cuisine"),
                    ("INDIAN", "Indian Cuisine"),
                    ("CHINESE", "Chinese Cuisine"),
                    ("JAPANESE", "Japanese Cuisine"),
                    ("MEXICAN", "Mexican Cuisine"),
                    ("MEDITERRANEAN", "Mediterranean Cuisine"),
                    ("AMERICAN", "American Cuisine"),
                    ("THAI", "Thai Cuisine"),
                    ("OTHER", "Other Cuisine"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
