# Generated by Django 4.2.20 on 2025-06-07 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_chefprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollowing",
            name="target_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_auth",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollowing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_auth",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
